version: '24.0.6'
services:
  top-api:
    image: docker.pkg.github.com/andriiserkhovetcdev/top-api/top-api:development
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env

