name: Publish Docker

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Publish to registy
            uses: elgohr/Publish-Docker-Github-Action@v5
            with:
              name: ghcr.io/${{ github.repository }}/top-api
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
              registry: ghcr.io
              tags: "development"
